package grimm.app;

import grimm.exception.GrimmException;
import grimm.model.Deadline;
import grimm.model.Event;
import grimm.model.Task;
import grimm.model.TaskList;
import grimm.model.ToDo;
import grimm.parse.Command;
import grimm.parse.Parser;
import grimm.storage.Storage;
import grimm.ui.Ui;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.DateTimeException;
import java.util.List;


/**
 * The main class that runs the Grimm application.
 * <p>
 * The Grimm class is responsible for handling the user input, processing commands, and managing tasks.
 * It interacts with various components such as the TaskList, Ui, and Storage to perform actions on tasks,
 * such as adding, marking, unmarking, deleting, and displaying tasks.
 * </p>
 */
public class Grimm {
    private final TaskList taskList;
    private final Ui ui;
    private final Parser parser;

    /**
     * Loads tasks from the default storage file into the task list.
     * <p>
     * Attempts to read tasks from the file located at "./data/grimm.txt" using the Storage class.
     * Each loaded task is added to the internal task list.
     * In case the file is not found or a Grimm-specific exception occurs,
     * appropriate UI error messages are displayed.
     * </p>
     */
    private void loadTasksFromFile() {
        try {
            Storage storage = new Storage("./data/grimm.txt");
            for (Task t : storage.load()) {
                this.taskList.add(t);
            }
        } catch (FileNotFoundException e) {
            this.ui.invalidFile();
        } catch (GrimmException e) {
            this.ui.invalidGrimmMsg(e.getMessage());
        }
    }

    /**
     * Modifies a task in the task list based on the specified command.
     * <p>
     * Parses the task index from the parser description, validates the index,
     * and performs the requested operation: mark, unmark, or delete.
     * Returns an appropriate UI message based on the operation result.
     * If the command is unrecognized or an error occurs, the method returns
     * a corresponding UI error or unknown command message.
     * </p>
     *
     * @param parser  The Parser object containing the user input and task index description.
     * @param command The Command enum indicating the modification operation to perform.
     * @return A string message generated by the UI reflecting the outcome of the operation.
     */
    private String modifyTasks(Parser parser, Command command) {
        try {
            int num = parser.parseInt();
            assert num > 0 : "Task index should exist in the list";
            this.taskList.checkExceedIndex(num);
            Task task;
            switch (command) {
                case MARK -> {
                    task = this.taskList.mark(num);
                    return this.ui.markMsg(task);
                }
                case UNMARK -> {
                    task = this.taskList.unmark(num);
                    return this.ui.unmarkMsg(task);
                }
                case DELETE -> {
                    task = this.taskList.delete(num);
                    return this.ui.deleteMsg(task, this.taskList);
                }
                default -> {
                    return this.ui.unknownCommand();
                }
            }
        } catch (GrimmException e) {
            return this.ui.invalidGrimmMsg(e.getMessage());
        }
    }

    /**
     * Constructs a Grimm object and initializes the taskList, UI, parser and storage.
     */
    public Grimm() {
        this.taskList = new TaskList();
        this.ui = new Ui();
        this.parser = new Parser();
        loadTasksFromFile();
    }

    /**
     * Generates a response for the user's chat message.
     *
     * <p>
     * The input is parsed into a Command and using
     * the Parser. The appropriate action is executed and a message
     * is returned via Ui.
     * </p>
     *
     * <p>
     * This method captures and converts internal exceptions into UI
     * messages; it does not show exceptions to the caller.
     * </p>
     *
     * @param input the raw user input string
     * @return a formatted response string to display to the user
     */
    public String getResponse(String input) {
        Parser parser = this.parser.parse(input);
        assert parser != null : "Parser should not be null";
        Command command = parser.getCommand();
        assert command != null : "Command should not be null";
        String desc = parser.getDesc();

        switch (command) {
            case BYE -> {
                try {
                    Storage storage = new Storage("./data/grimm.txt");
                    storage.save(this.taskList.getTaskList());
                } catch (IOException e) {
                    return this.ui.invalidFile();
                }

                return this.ui.bye();
            }
            case LIST -> {
                return this.ui.showTasks(this.taskList.getTaskList());
            }
            case MARK -> {
                return modifyTasks(parser, command);
            }
            case UNMARK -> {
                return modifyTasks(parser, command);
            }
            case TODO -> {
                try {
                    parser.checkValidName();
                    ToDo todo = new ToDo(desc);
                    this.taskList.add(todo);
                    return this.ui.addMsg(todo, this.taskList.getSize());
                } catch (GrimmException e) {
                    return this.ui.invalidGrimmMsg(e.getMessage());
                }
            }

            case DEADLINE -> {
                try {
                    String[] descParts = parser.parseDeadline();
                    Deadline deadline = new Deadline(descParts[0], descParts[1]);
                    this.taskList.add(deadline);
                    return this.ui.addMsg(deadline, this.taskList.getSize());
                } catch (GrimmException e) {
                    return this.ui.invalidDeadline();
                } catch (DateTimeException e) {
                    return this.ui.invalidDate();
                }
            }
            case EVENT -> {
                try {
                    String[] descParts = parser.parseEvent();
                    Event event = new Event(descParts[0], descParts[1], descParts[2]);
                    this.taskList.add(event);
                    return this.ui.addMsg(event, this.taskList.getSize());
                } catch (GrimmException e) {
                    return this.ui.invalidEvent();
                } catch (DateTimeException e) {
                    return this.ui.invalidDatetime();
                }
            }
            case DELETE -> {
                return modifyTasks(parser, command);
            }
            case FIND -> {
                List<Task> filteredTaskList = this.taskList.findTask(desc);
                if (filteredTaskList.isEmpty()) {
                    return this.ui.listEmptyMsg();
                } else {
                    return this.ui.showTasks(filteredTaskList);
                }
            }
            default -> {
                return this.ui.unknownCommand();
            }
        }
    }

    /**
     * The main method that runs the Grimm application.
     * <p>
     * This method initializes the application, loads tasks from a storage file,
     * and listens for user commands to interact with the task list. It also handles
     * saving the tasks back to the file upon exiting the application.
     * </p>
     *
     * @param args The command-line arguments passed to the application.
     */
    public static void main(String[] args) {
        System.out.println("Silksong is finally here");
    }

}
